config/routes.rb
Rails.application.routes.draw do

  resources :gossips
  root to: 'static_pages#home'
  get 'gossips/new'
  get 'gossips/edit', to: 'gossips#edit'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  validates :user, presence: false, uniqueness: false
  belongs_to :gossip
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  has_and_belongs_to_many :tags
  has_many :comments
  has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip, optional: true
  belongs_to :comment, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, :class_name=>'User', :foreign_key=>'sender_id'
  belongs_to :receiver, :class_name=>'User', :foreign_key=>'receiver_id'
  belongs_to :receiver2, :class_name=>'User', :foreign_key=>'receiver2_id', optional: true
  belongs_to :receiver3, :class_name=>'User', :foreign_key=>'receiver3_id', optional: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :gossips, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  belongs_to :city
  has_many :sent_messages, :class_name => "Message", :foreign_key => "sender_id"
  has_many :received_messages, :class_name => "Message", :foreign_key => "receiver_id"
  has_many :received_messages, :class_name => "Message", :foreign_key => "receiver2_id"
  has_many :received_messages, :class_name => "Message", :foreign_key => "receiver3_id"
  has_many :gossips
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def index

  end

  def update
     @gossip = Gossip.find(params[:id])
     post_params = params.require(:gossip).permit(:title, :content, :anonymous_gossiper)
     @gossip.update(post_params)
     redirect_to @gossip
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end



  def show
    @gossip = Gossip.find(params[:id])
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to '/'
  end

  def new
  end



  def create
    @gossip = Gossip.new(gossip_params)
    if @gossip.save
      redirect_to @gossip
    else
      render 'new'
    end
  end

  private
    def gossip_params
      params.require(:gossip).permit(:title, :content, :anonymous_gossiper)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/gossips/create.html.erb
<h1>Gossips#create</h1>
<p>Find me in app/views/gossips/create.html.erb</p>

app/views/gossips/edit.html.erb
<h2>Edit user</h2>

<%= form_for @gossip do |f| %>
<div class="form-group">
  <label> Titre de l'article</label>
  <%= f.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
  <label> Contenu de l'article</label>
  <%= f.text_area :content, class: 'form-control' %>
</div>

<div class="form-group">
  <label> Nom du Anonymous Gossiper</label>
  <%= f.text_field :anonymous_gossiper, class: 'form-control' %>
</div>

<div class="form-group">
  <button type="submit" class="btn btn-primary">Modifier le Gossip</button>
</div>
<% end %>

app/views/gossips/index.html.erb
 Il y a un total de <%= Comment.all.size %> commentaires.

app/views/gossips/new.html.erb
<section class="new">
  <h1>New Gossip</h1>

  <%= form_with scope: :gossip, url: gossips_path, local: true do |form| %>
    <div class="form-group">
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </div>

    <div class="form-group">
      <%= form.label :content %><br>
      <%= form.text_area :content %>
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary">Sauvegarder le Gossip</button>
    </div>

  <% end %>

  <%= form_with scope: :gossip, url: gossips_path, local: true do |form| %>
<form>
  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <div class="form-group">
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
  <% end %>

  </section>

app/views/gossips/show.html.erb
<h1>Voici la page de ton Gossip</h1>
<p>ID</p>
<p><%= @gossip.id %></p>
<hr>
<p>User_ID</p>
<p><%= @gossip.user_id %></p>
<hr>
<p>
  <strong>Title:</strong>
  <%= @gossip.title %>
</p>
<hr>
<p>
  <strong>Contenu:</strong>
  <%= @gossip.content %>
</p>
<hr>
<p>
  <strong>Anonymous_gossiper:</strong>
  <%= @gossip.anonymous_gossiper %>
</p>

<a href="/gossips/<%=params[:id]%>/edit" class="btn btn-primary">Edit</a><br><br>

<%= link_to 'Détruire le Gossip ', @gossip, method: :delete, class: 'btn btn-danger' %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Heroku on Rails</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <span class="nav-link"><%= link_to "Accueil",   '/' %></span>
        </li>
        <li class="nav-item">
          <span class="nav-link"><%= link_to "Index des gossips", '/gossips' %></span>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <span class="btn btn-primary"><%= link_to "Nouveau gossip", '/gossips/new' %></span>
        </li>
      </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <title>TheFuckingGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'layouts/header' %>

      <center>

          <%= yield %>
        
      </center>


  </body>
</html>

app/views/static_pages/home.html.erb
<section class='CTA'>
  <div class="container">
    <div class="row align-items-center section">
      <div class="col-md-2"></div>
      <div class="col-8">
        <h1>Bienvenue !</h1>
        <br>
        <br>
        <h3>Ici, tu peux retrouver les moussaillons 🎓</h3>
        <br>
        <%= link_to "Enregistre-toi !", '/gossips/new', class: "btn btn-lg btn-primary" %>
      </div>
      <div class="col-md-2"></div>
    </div>



  </div>
</section>